In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame(np.random.rand(250,5),index=np.arange(250))

In [3]:
df

            0         1         2         3         4
0    0.511939  0.319122  0.919581  0.243781  0.331852
1    0.499012  0.089149  0.828849  0.266204  0.460953
2    0.496435  0.326330  0.287737  0.316973  0.783848
3    0.815338  0.407026  0.761360  0.583070  0.211999
4    0.464071  0.074727  0.391257  0.306166  0.145035
..        ...       ...       ...       ...       ...
245  0.453614  0.944478  0.993880  0.630533  0.127551
246  0.335668  0.488806  0.424501  0.804961  0.302488
247  0.187836  0.668457  0.603565  0.997447  0.028199
248  0.473877  0.593394  0.819703  0.680547  0.752840
249  0.322341  0.486056  0.105393  0.915269  0.503206

[250 rows x 5 columns]

**We can solve complex queries in database in pandas very easily**

In [4]:
df.columns=list("ABCDE")

In [5]:
df.head(2)

          A         B         C         D         E
0  0.511939  0.319122  0.919581  0.243781  0.331852
1  0.499012  0.089149  0.828849  0.266204  0.460953

In [9]:
df.loc[df['A']<0.3]

            A         B         C         D         E
5    0.014893  0.085339  0.718959  0.084374  0.020806
6    0.067592  0.813338  0.147605  0.355065  0.993944
9    0.290971  0.324139  0.598406  0.405033  0.411703
10   0.176717  0.750932  0.289322  0.289136  0.902178
16   0.256247  0.817264  0.207966  0.211846  0.238592
..        ...       ...       ...       ...       ...
234  0.181754  0.547670  0.059176  0.780951  0.609481
235  0.246363  0.726887  0.397151  0.819980  0.607397
240  0.222392  0.314534  0.190182  0.077943  0.301201
244  0.207216  0.357022  0.021823  0.007144  0.881952
247  0.187836  0.668457  0.603565  0.997447  0.028199

[67 rows x 5 columns]

In [11]:
df.loc[(df['B']<0.3) & (df['D']>0.2)]

            A         B         C         D         E
1    0.499012  0.089149  0.828849  0.266204  0.460953
4    0.464071  0.074727  0.391257  0.306166  0.145035
17   0.805173  0.077061  0.921065  0.309449  0.965956
20   0.027003  0.183780  0.323059  0.694095  0.562182
24   0.482879  0.089236  0.624858  0.674951  0.990560
27   0.596201  0.298431  0.497431  0.502149  0.238000
44   0.255102  0.132116  0.124934  0.410723  0.441422
47   0.603019  0.267955  0.200938  0.665710  0.661623
50   0.866577  0.261213  0.187822  0.648201  0.750810
51   0.285731  0.179512  0.759578  0.614154  0.392536
56   0.375662  0.156859  0.509045  0.949013  0.924016
58   0.355733  0.115113  0.362866  0.645457  0.359637
64   0.925899  0.095477  0.439390  0.292222  0.252908
71   0.858804  0.062029  0.213522  0.969016  0.855752
72   0.330462  0.136363  0.936397  0.672940  0.625411
75   0.876930  0.056178  0.176210  0.866033  0.196444
76   0.690583  0.162163  0.930444  0.966059  0.079580
78   0.042286  0.131429  0.447068  0.955571  0.718742
85   0.255809  0.214833  0.483290  0.965675  0.425007
92   0.666795  0.084274  0.055455  0.407494  0.803553
96   0.541080  0.209642  0.685016  0.414508  0.439181
97   0.978856  0.151046  0.593062  0.289302  0.478073
99   0.109813  0.278441  0.997089  0.424903  0.805248
103  0.890030  0.198696  0.737936  0.848722  0.202844
106  0.034205  0.001992  0.148507  0.638492  0.653380
107  0.380671  0.140737  0.534901  0.809281  0.690414
114  0.910909  0.146683  0.856350  0.327278  0.902275
116  0.438527  0.156276  0.567297  0.770196  0.304611
125  0.655611  0.297768  0.379509  0.233681  0.149617
126  0.602932  0.224950  0.664685  0.709465  0.278962
127  0.257470  0.031832  0.215425  0.400770  0.495625
133  0.375827  0.003551  0.260553  0.655394  0.423024
134  0.839800  0.033682  0.700082  0.611538  0.683343
139  0.456182  0.251201  0.877455  0.380507  0.419533
144  0.959496  0.291617  0.112255  0.386438  0.138310
145  0.996671  0.116559  0.706114  0.434209  0.286412
150  0.292362  0.059527  0.002583  0.868916  0.814610
151  0.399689  0.263205  0.257304  0.298640  0.498477
152  0.552537  0.233730  0.403467  0.990429  0.734265
153  0.724060  0.249861  0.304136  0.543074  0.970632
154  0.562930  0.008771  0.439182  0.590285  0.960603
156  0.801718  0.272475  0.567337  0.967132  0.645956
158  0.229093  0.104878  0.998323  0.853860  0.097232
160  0.860856  0.031243  0.428151  0.836484  0.033914
162  0.942408  0.052734  0.510188  0.639299  0.656123
169  0.369417  0.016507  0.903523  0.610761  0.374932
171  0.517050  0.102174  0.607019  0.588511  0.526141
175  0.787787  0.122000  0.094926  0.619111  0.279929
180  0.311674  0.293298  0.850837  0.669856  0.924758
188  0.120069  0.283097  0.956458  0.666002  0.642329
193  0.745289  0.219796  0.927558  0.279960  0.151640
197  0.622096  0.077458  0.861469  0.280192  0.580294
199  0.758974  0.033943  0.048451  0.957183  0.152462
215  0.279106  0.178987  0.257867  0.326354  0.152074
220  0.247593  0.256204  0.225863  0.331768  0.207632
229  0.146640  0.114740  0.906815  0.309313  0.230982
238  0.746042  0.013651  0.771145  0.862674  0.888008
243  0.953627  0.094310  0.916721  0.787202  0.084462

In [ ]:
df